name: 检查文档可编译性
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_doc_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 将文档编译为 HTML
      run: |
        git submodule update --init --depth=1
        pushd taichi && git checkout master && popd
        make all
        make html
